# Generated by Django 5.2.6 on 2025-09-21 03:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('companies', '0002_officelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('inperson', 'In person')], default='online', max_length=10)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_emp_approval', 'Pending EMP approval'), ('awaiting_candidate', 'Awaiting candidate'), ('awaiting_emp_confirm', 'Awaiting EMP confirm'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_candidate', max_length=24)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=128)),
                ('zoom_join_url', models.URLField(blank=True)),
                ('zoom_start_url', models.URLField(blank=True)),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_48h_sent', models.BooleanField(default=False)),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('notes_md', models.TextField(blank=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='interview_recordings/')),
                ('transcript_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.officelocation')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewInterviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='e.g., Panelist, Lead, HR', max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_as_interviewer', to='companies.employee')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewers', to='interviews.interview')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_bookable', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='companies.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'start'], name='interviews__employe_94bd7e_idx'), models.Index(fields=['is_bookable'], name='interviews__is_book_1a8a8e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['application', 'status'], name='interviews__applica_96ea9d_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['start'], name='interviews__start_ba7f1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewinterviewer',
            unique_together={('interview', 'employee')},
        ),
    ]
