# Generated by Django 5.2.6 on 2025-09-21 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., HQ – Floor 5', max_length=120)),
                ('address', models.TextField(blank=True)),
                ('room', models.CharField(blank=True, help_text='e.g., Room 5A', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'label'], name='companies_o_company_4af40f_idx')],
                'unique_together': {('company', 'label', 'room')},
            },
        ),
    ]
