# Generated by Django 5.2.6 on 2025-09-21 03:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('manager_name', models.CharField(blank=True, max_length=150)),
                ('emp_type', models.CharField(blank=True, max_length=50)),
                ('location_mode', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='hybrid', max_length=10)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('role_purpose', models.TextField(blank=True)),
                ('description_md', models.TextField(blank=True)),
                ('responsibilities_md', models.TextField(blank=True)),
                ('req_quals', models.JSONField(blank=True, default=list)),
                ('pref_quals', models.JSONField(blank=True, default=list)),
                ('perf_metrics', models.JSONField(blank=True, default=list)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=8)),
                ('pay_period', models.CharField(blank=True, default='year', max_length=16)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('visa_sponsorship', models.BooleanField(default=False)),
                ('background_check_required', models.BooleanField(default=False)),
                ('security_clearance', models.CharField(blank=True, max_length=64)),
                ('eeo_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('paused', 'Paused')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manages_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='invited', max_length=12)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='companies.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='jobs.job')),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status'], name='jobs_job_company_797da4_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='jobs_job_title_0e1e41_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['deadline'], name='jobs_job_deadlin_c19edf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobassignee',
            unique_together={('job', 'employee')},
        ),
    ]
