# Generated by Django 5.2.6 on 2025-09-21 03:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/apps/')),
                ('profile_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('ats_screen', 'ats_screen'), ('employee_review', 'employee_review'), ('interview_pending', 'interview_pending'), ('interview_scheduled', 'interview_scheduled'), ('under_consideration', 'under_consideration'), ('rejected', 'rejected'), ('offer', 'offer'), ('hired', 'hired')], default='submitted', max_length=32)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('decision', models.CharField(blank=True, max_length=12)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='applications.application')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_assignments', to='companies.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.IntegerField(default=0)),
                ('reasons', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='applications.application')),
            ],
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='application_job_id_7836e3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='application_user_id_55b4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_c6d08d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'user')},
        ),
        migrations.AddIndex(
            model_name='applicationassignment',
            index=models.Index(fields=['employee'], name='application_employe_39526e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationassignment',
            index=models.Index(fields=['application'], name='application_applica_6ff74d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationassignment',
            unique_together={('application', 'employee')},
        ),
    ]
