# Generated by Django 5.2.6 on 2025-09-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ats_outcome',
            field=models.CharField(choices=[('pass', 'Pass'), ('below', 'Below threshold')], default='below', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ats_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
